name: Docker build nitter image

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "::set-output name=commit::$(git ls-remote https://github.com/zedeus/nitter.git | head -n1 | awk '{print $1;}')"
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: nitter
          key: ${{ runner.os }}-v11-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v2
          
      - name: Check Out Repo goodtiding5/docker-nitter
        uses: actions/checkout@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "goodtiding5/docker-nitter"
          ref: 'master'
          path: 'nitter-git'
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Copy override files for nitter
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cp ./nitter/* ./nitter-git
        shell: bash

      - name: Apply normal patch
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ./nitter-git
          patch Dockerfile < normal.patch
        shell: bash

      - name: Build and push docker image
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new
        uses: docker/build-push-action@v2
        with:
          context: ./nitter-git
          file: ./nitter-git/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ceramicwhite/nitter:dev #, ceramicwhite/nitter:build-${{ env.timestamp }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}